"""Minimal OpenAI-compatible proxy to Lunit L2."""

from __future__ import annotations

import argparse
import json
import logging
import os
import socket
import time
import uuid
from collections.abc import Callable, Mapping, Sequence
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import Request, urlopen

MODEL_ID = "team-chatbot"
DEFAULT_L2_API_URL = "https://model.hackathon.lunit.io"
DEFAULT_L2_MODEL = "Lunit/L2-preview"
L2_TIMEOUT_SECONDS = 35.0
L2_MAX_TOKENS = 1_536
MAX_REQUEST_BYTES = 1_000_000
MAX_RESPONSE_BYTES = 4_000_000

_PLACEHOLDER_API_KEYS = {"", "여기에_직접_입력", "lunit_replace_me"}
_LOCAL_ENV_KEYS = {"LUNIT_FM_API_URL", "LUNIT_FM_API_KEY", "LUNIT_FM_MODEL"}
logger = logging.getLogger("brave_tylenol")


class ClientRequestError(ValueError):
    """The evaluator request is not a supported chat-completion request."""


class ConfigurationError(RuntimeError):
    """The official L2 endpoint or credential is unavailable."""


class L2ResponseError(RuntimeError):
    """L2 did not return a usable completion."""


class L2TimeoutError(L2ResponseError):
    """The single upstream L2 request exceeded its deadline."""


CompletionProvider = Callable[[dict[str, Any], str | None], dict[str, Any]]


class L2ProxyServer(ThreadingHTTPServer):
    """Concurrent server that delegates every successful answer to L2."""

    allow_reuse_address = True
    daemon_threads = True
    request_queue_size = 128

    def __init__(
        self,
        server_address: tuple[str, int],
        handler_class: type[BaseHTTPRequestHandler],
        *,
        completion_provider: CompletionProvider | None = None,
    ) -> None:
        super().__init__(server_address, handler_class)
        self.completion_provider = completion_provider or request_l2_completion


def models_payload() -> dict[str, Any]:
    return {
        "object": "list",
        "data": [
            {
                "id": MODEL_ID,
                "object": "model",
                "created": 0,
                "owned_by": "brave-tylenol",
            }
        ],
    }


def completion_payload(
    content: str,
    *,
    finish_reason: str = "stop",
    usage: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Wrap text already generated by L2 for the evaluator-facing API."""

    return {
        "id": f"chatcmpl-{uuid.uuid4().hex}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": MODEL_ID,
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": content},
                "finish_reason": (finish_reason if finish_reason in {"stop", "length"} else "stop"),
            }
        ],
        "usage": _normalized_usage(usage),
    }


def error_payload(message: str, error_type: str, code: str) -> dict[str, Any]:
    return {
        "error": {
            "message": message,
            "type": error_type,
            "code": code,
        }
    }


def request_l2_completion(
    request_payload: dict[str, Any],
    authorization: str | None,
    *,
    opener: Callable[..., Any] | None = None,
    environ: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Make exactly one bounded L2 request and return its final text."""

    environment = os.environ if environ is None else environ
    api_key = _bearer_token(authorization) or _configured_api_key(environment)
    if api_key is None:
        raise ConfigurationError("L2 API credential is unavailable")

    upstream_payload = {
        "model": _configured_model(environment),
        "messages": _normalized_messages(request_payload.get("messages")),
        "max_tokens": _completion_token_budget(request_payload),
        "temperature": 0.0,
        "stream": False,
    }
    encoded_payload = json.dumps(
        upstream_payload,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    upstream_request = Request(
        _chat_completions_url(environment),
        data=encoded_payload,
        headers={
            "Accept": "application/json",
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json; charset=utf-8",
            "Connection": "close",
            "User-Agent": "BraveTylenol-L2-Proxy/2.0",
        },
        method="POST",
    )

    started = time.monotonic()
    try:
        with (opener or urlopen)(
            upstream_request,
            timeout=L2_TIMEOUT_SECONDS,
        ) as response:
            status = int(getattr(response, "status", HTTPStatus.OK))
            raw_response = response.read(MAX_RESPONSE_BYTES + 1)
    except HTTPError as error:
        raise L2ResponseError("L2 returned an unsuccessful status") from error
    except URLError as error:
        if _is_timeout_error(error.reason):
            raise L2TimeoutError("L2 request timed out") from error
        raise L2ResponseError("L2 transport failed") from error
    except OSError as error:
        if _is_timeout_error(error):
            raise L2TimeoutError("L2 request timed out") from error
        raise L2ResponseError("L2 transport failed") from error

    if not 200 <= status < 300:
        raise L2ResponseError("L2 returned an unsuccessful status")
    if len(raw_response) > MAX_RESPONSE_BYTES:
        raise L2ResponseError("L2 response exceeded the size limit")

    content, finish_reason, usage = _parse_l2_completion(raw_response)
    logger.info("L2 completion succeeded in %.2fs", time.monotonic() - started)
    return completion_payload(content, finish_reason=finish_reason, usage=usage)


def _parse_l2_completion(
    raw_response: bytes,
) -> tuple[str, str, Mapping[str, Any] | None]:
    try:
        upstream = json.loads(raw_response.decode("utf-8"))
        if not isinstance(upstream, Mapping):
            raise ValueError("response is not an object")
        choices = upstream.get("choices")
        if not isinstance(choices, list) or not choices:
            raise ValueError("response has no choices")
        choice = choices[0]
        if not isinstance(choice, Mapping):
            raise ValueError("choice is not an object")
        message = choice.get("message")
        if not isinstance(message, Mapping):
            raise ValueError("choice has no message")
        content = _text_content(message.get("content"))
        if content is None or not content.strip():
            raise ValueError("L2 returned blank content")
        finish_reason = choice.get("finish_reason", "stop")
        usage = upstream.get("usage")
    except (UnicodeDecodeError, json.JSONDecodeError, TypeError, ValueError) as error:
        raise L2ResponseError("L2 returned an invalid completion") from error

    return (
        content.strip(),
        finish_reason if isinstance(finish_reason, str) else "stop",
        usage if isinstance(usage, Mapping) else None,
    )


def _normalized_messages(value: Any) -> list[dict[str, str]]:
    if not isinstance(value, list) or not value:
        raise ClientRequestError("messages must be a non-empty array")

    normalized: list[dict[str, str]] = []
    total_characters = 0
    has_user_message = False
    for message in value:
        if not isinstance(message, Mapping):
            raise ClientRequestError("each message must be an object")
        role = message.get("role")
        if role == "developer":
            role = "system"
        if role not in {"system", "user", "assistant"}:
            raise ClientRequestError("unsupported message role")
        content = _text_content(message.get("content"))
        if content is None:
            raise ClientRequestError("message content must contain text")
        total_characters += len(content)
        if total_characters > 500_000:
            raise ClientRequestError("message content is too large")
        has_user_message = has_user_message or role == "user"
        normalized.append({"role": role, "content": content})

    if not has_user_message:
        raise ClientRequestError("messages must contain a user message")
    return normalized


def _text_content(value: Any) -> str | None:
    if isinstance(value, str):
        return value
    if not isinstance(value, list):
        return None

    parts: list[str] = []
    for part in value:
        if not isinstance(part, Mapping):
            return None
        if part.get("type") not in {"text", "input_text"}:
            return None
        text = part.get("text")
        if not isinstance(text, str):
            return None
        parts.append(text)
    return "".join(parts)


def _completion_token_budget(request_payload: Mapping[str, Any]) -> int:
    requested = request_payload.get("max_tokens")
    if not isinstance(requested, int) or isinstance(requested, bool) or requested <= 0:
        return L2_MAX_TOKENS
    return min(requested, L2_MAX_TOKENS)


def _normalized_usage(usage: Mapping[str, Any] | None) -> dict[str, int]:
    source = usage if isinstance(usage, Mapping) else {}

    def count(name: str) -> int:
        value = source.get(name, 0)
        if isinstance(value, int) and not isinstance(value, bool):
            return max(0, value)
        return 0

    prompt_tokens = count("prompt_tokens")
    completion_tokens = count("completion_tokens")
    total_tokens = count("total_tokens") or prompt_tokens + completion_tokens
    return {
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens,
    }


def _bearer_token(authorization: str | None) -> str | None:
    if not authorization:
        return None
    scheme, separator, token = authorization.partition(" ")
    if not separator or scheme.casefold() != "bearer":
        return None
    return token.strip() or None


def _configured_api_key(environment: Mapping[str, str]) -> str | None:
    value = environment.get("LUNIT_FM_API_KEY", "").strip()
    return value if value not in _PLACEHOLDER_API_KEYS else None


def _configured_model(environment: Mapping[str, str]) -> str:
    model = environment.get("LUNIT_FM_MODEL", DEFAULT_L2_MODEL).strip()
    return model or DEFAULT_L2_MODEL


def _chat_completions_url(environment: Mapping[str, str]) -> str:
    base_url = environment.get("LUNIT_FM_API_URL", DEFAULT_L2_API_URL).strip()
    base_url = (base_url or DEFAULT_L2_API_URL).rstrip("/")
    parsed = urlsplit(base_url)
    if parsed.scheme != "https" or parsed.hostname != "model.hackathon.lunit.io":
        raise ConfigurationError("L2 API URL must use the official HTTPS endpoint")
    if parsed.path.rstrip("/").endswith("/v1/chat/completions"):
        return base_url
    if parsed.path.rstrip("/").endswith("/v1"):
        return f"{base_url}/chat/completions"
    return f"{base_url}/v1/chat/completions"


def _is_timeout_error(error: object) -> bool:
    return isinstance(error, (TimeoutError, socket.timeout))


def load_local_env(path: str | Path = ".env") -> None:
    """Load only L2 settings from a local .env without third-party packages."""

    env_path = Path(path)
    if not env_path.is_file():
        return
    try:
        lines = env_path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key not in _LOCAL_ENV_KEYS or key in os.environ:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        os.environ[key] = value


class L2ProxyHandler(BaseHTTPRequestHandler):
    """OpenAI-shaped endpoints backed by one bounded L2 request."""

    protocol_version = "HTTP/1.1"
    server_version = "BraveTylenolL2Proxy/2.0"
    sys_version = ""

    @property
    def proxy_server(self) -> L2ProxyServer:
        return self.server  # type: ignore[return-value]

    def log_message(self, format: str, *args: Any) -> None:
        # Never log request headers, medical text, or credentials.
        logger.info("HTTP %s", format % args)

    def _path(self) -> str:
        path = urlsplit(self.path).path.rstrip("/")
        return path or "/"

    def _send_json(
        self,
        status: HTTPStatus,
        payload: dict[str, Any],
        *,
        include_body: bool = True,
    ) -> None:
        body = json.dumps(
            payload,
            ensure_ascii=False,
            separators=(",", ":"),
        ).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "close")
        self.end_headers()
        if include_body:
            try:
                self.wfile.write(body)
            except (BrokenPipeError, ConnectionResetError):
                pass
        self.close_connection = True

    def _get_payload(self) -> tuple[HTTPStatus, dict[str, Any]]:
        path = self._path()
        if path in {"/health", "/healthz"}:
            return HTTPStatus.OK, {"status": "ok"}
        if path == "/v1/models":
            return HTTPStatus.OK, models_payload()
        if path == "/":
            return HTTPStatus.OK, {"status": "ok", "mode": "lunit-l2-proxy"}
        return HTTPStatus.NOT_FOUND, {"detail": "Not found"}

    def _read_request_payload(self) -> dict[str, Any]:
        try:
            content_length = int(self.headers.get("Content-Length") or "0")
        except ValueError as error:
            raise ClientRequestError("invalid Content-Length") from error
        if content_length <= 0:
            raise ClientRequestError("request body is required")
        if content_length > MAX_REQUEST_BYTES:
            raise ClientRequestError("request body is too large")
        try:
            self.connection.settimeout(5.0)
            payload = json.loads(self.rfile.read(content_length).decode("utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
            raise ClientRequestError("request body must be valid JSON") from error
        if not isinstance(payload, dict):
            raise ClientRequestError("request body must be a JSON object")
        if payload.get("stream") is True:
            raise ClientRequestError("streaming responses are not supported")
        return payload

    def do_GET(self) -> None:
        status, payload = self._get_payload()
        self._send_json(status, payload)

    def do_HEAD(self) -> None:
        status, payload = self._get_payload()
        self._send_json(status, payload, include_body=False)

    def do_POST(self) -> None:
        if self._path() != "/v1/chat/completions":
            self._send_json(HTTPStatus.NOT_FOUND, {"detail": "Not found"})
            return

        try:
            request_payload = self._read_request_payload()
            response_payload = self.proxy_server.completion_provider(
                request_payload,
                self.headers.get("Authorization"),
            )
        except ClientRequestError:
            self._send_json(
                HTTPStatus.BAD_REQUEST,
                error_payload(
                    "Invalid chat completion request",
                    "invalid_request_error",
                    "invalid_request",
                ),
            )
            return
        except ConfigurationError:
            logger.warning("L2 request rejected: configuration unavailable")
            self._send_json(
                HTTPStatus.SERVICE_UNAVAILABLE,
                error_payload(
                    "L2 is not configured",
                    "service_unavailable",
                    "l2_not_configured",
                ),
            )
            return
        except L2TimeoutError:
            logger.warning("L2 request failed: timeout")
            self._send_json(
                HTTPStatus.GATEWAY_TIMEOUT,
                error_payload("L2 request timed out", "timeout_error", "l2_timeout"),
            )
            return
        except L2ResponseError:
            logger.warning("L2 request failed: upstream response")
            self._send_json(
                HTTPStatus.BAD_GATEWAY,
                error_payload("L2 request failed", "upstream_error", "l2_failure"),
            )
            return
        except Exception:
            logger.exception("Unexpected completion failure")
            self._send_json(
                HTTPStatus.INTERNAL_SERVER_ERROR,
                error_payload("Internal server error", "server_error", "internal_error"),
            )
            return

        self._send_json(HTTPStatus.OK, response_payload)

    def do_OPTIONS(self) -> None:
        self.send_response(HTTPStatus.NO_CONTENT)
        self.send_header("Allow", "GET, HEAD, POST, OPTIONS")
        self.send_header("Content-Length", "0")
        self.send_header("Connection", "close")
        self.end_headers()
        self.close_connection = True


def create_server(
    host: str = "0.0.0.0",
    port: int = 8000,
    *,
    completion_provider: CompletionProvider | None = None,
) -> L2ProxyServer:
    return L2ProxyServer(
        (host, port),
        L2ProxyHandler,
        completion_provider=completion_provider,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run the minimal Lunit L2 proxy")
    parser.add_argument("command", nargs="?", default="serve", choices=["serve"])
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    load_local_env()
    logging.basicConfig(
        level=os.environ.get("LOG_LEVEL", "INFO").upper(),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    server = create_server(args.host, args.port)
    logger.info("L2 proxy listening on %s:%s", args.host, args.port)
    try:
        server.serve_forever(poll_interval=0.1)
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
